/**
 * Sprint C.6 — provenance tracking (Karpathy pattern).
 *
 * Every artifact Mutly produces (plan, build step, commit, review
 * note) carries a `Provenance` object. Reviewers can re-run the same
 * prompt and compare output. Required when workflow.provenance_required
 * is true (default).
 *
 *   {
 *     origin: "human" | "ai" | "mixed",
 *     actor: "Mutly Agent" | "<reviewer-name>" | ...,
 *     promptHash: "sha256:..." | null,    // null for human-authored
 *     model: "claude-sonnet-4-5" | null,
 *     workflowHash: "sha256:...",          // pins the workflow state
 *     timestamp: 1700000000000,
 *   }
 */
import { createHash } from "crypto";
import fs from "fs";
import path from "path";

export type ProvenanceOrigin = "human" | "ai" | "mixed";

export interface Provenance {
  origin: ProvenanceOrigin;
  actor: string;
  promptHash: string | null;
  model: string | null;
  workflowHash: string;
  timestamp: number;
  /** Optional note about the artifact (e.g. "auto-generated by planAgent"). */
  note?: string;
}

export function sha256(s: string): string {
  return "sha256:" + createHash("sha256").update(s, "utf-8").digest("hex").slice(0, 16);
}

/** Hash a file's contents (for snapshot diff comparisons). */
export function sha256File(filePath: string): string {
  if (!fs.existsSync(filePath)) return "sha256:missing";
  const content = fs.readFileSync(filePath, "utf-8");
  return sha256(content);
}

/** Build a provenance object for an AI-authored artifact. */
export function aiProvenance(opts: {
  prompt: string;
  model: string;
  actor?: string;
  workflowHash: string;
  note?: string;
}): Provenance {
  return {
    origin: "ai",
    actor: opts.actor ?? "Mutly Agent",
    promptHash: sha256(opts.prompt),
    model: opts.model,
    workflowHash: opts.workflowHash,
    timestamp: Date.now(),
    note: opts.note,
  };
}

/** Build a provenance object for a human-authored artifact. */
export function humanProvenance(opts: {
  actor: string;
  workflowHash: string;
  note?: string;
}): Provenance {
  return {
    origin: "human",
    actor: opts.actor,
    promptHash: null,
    model: null,
    workflowHash: opts.workflowHash,
    timestamp: Date.now(),
    note: opts.note,
  };
}

/** Attach a provenance to a JSON-serializable artifact. */
export function stamp<T extends Record<string, unknown>>(artifact: T, prov: Provenance): T & { _provenance: Provenance } {
  return { ...artifact, _provenance: prov };
}

/**
 * Compute the hash of a workflow config (so two workflow files with
 * the same effective config produce the same workflowHash).
 */
export function workflowHash(cfg: { risk: string; max_iterations: number; objective: string }): string {
  const canonical = JSON.stringify({ risk: cfg.risk, max_iterations: cfg.max_iterations, objective: cfg.objective.trim() });
  return sha256(canonical);
}

/** Pretty-print a provenance for logs. */
export function formatProvenance(p: Provenance): string {
  const bits = [
    `${p.origin}@${p.actor}`,
    p.model ? `model=${p.model}` : null,
    p.promptHash ? `prompt=${p.promptHash}` : null,
    `wf=${p.workflowHash}`,
  ].filter(Boolean);
  return bits.join(" ");
}
